### ISSUE TITLE
[Sugestão] Colocar campo para 3o Horário

### ISSUE THREAD

**Issue by duduribeiro** [brunozrk/click#21]
Quando realizamos viagens para o cliente, realizamos horário de jantar. Seria interessante uma opção para mais uma entrada e saída

:smile:

**Comment by fpgentil** [comment]
Na verdade acho que seria interessante colocar entradas/saídas de maneira dinâmica, assim não fica limitado a 2, ou 3.

**Comment by AugustoGu** [comment]
Concordo com a ideia dinamica dos horarios.

**Comment by Brunozrk** [comment]
Do jeito que está hoje, o mais fácil seria adicionar mais uma entrada/saída.

O que vocês sugerem?

Fiquem a vontade pra mandar PR se quiserem :sweat_smile: :laughing:

**Comment by brunozrk** [comment]
Feito https://github.com/brunozrk/click/pull/34
