### ISSUE TITLE
Remover timepicker quando o foco sair do componente.

### ISSUE THREAD

**Issue by fpgentil** [brunozrk/click#23]
Quando o foco sair do componente, acho que é melhor dar um hide nesse timepicker, o que acha?

![bildschirmfoto 2015-04-02 um 13 13 12](https://cloud.githubusercontent.com/assets/356881/6968088/5276ef7a-d93a-11e4-8449-c90bbf4a435c.png)

**Comment by Brunozrk** [comment]
Boa, isso me incomoda tbm hahah

**Comment by Brunozrk** [comment]
Fiz a mudança la, da uma olhada, ve o que achou

**Comment by fpgentil** [comment]
Acho que pode fechar esse issue :smile:

**Comment by brunozrk** [comment]
:+1:
