### ISSUE TITLE
Configuração de Horas de trabalho por dia

### ISSUE THREAD

**Issue by jpcercal** [brunozrk/click#31]
Acredito que isto seja uma realidade não só para mim, mas também para outras pessoas.

Acho que seria interessante que o sistema permisse configurar um horário de trabalho por dia igual à "08:30" ou "08:48" conforme a CLT. Hoje o sistema permite apenas o cadastro de 8 horas ou 9 horas.

**Comment by brunozrk** [comment]
Hum, concordo, no meu caso serviu para número inteiro, não tinha pensado nisso, boa @jpcercal !

**Comment by jpcercal** [comment]
Bacana a implementação do @fpgentil, ancioso pra usar o recurso no app após a atualização.. Obrigado @brunozrk!

**Comment by brunozrk** [comment]
Feito, boa galera! :clap:
