### ISSUE TITLE
[Sugestão] Incluir configuração de tempo máximo entre período e "almoço"

### ISSUE THREAD

**Issue by fpgentil** [brunozrk/click#32]
Estive pensando, e acho que seria interessante incluir outras configurações. Hoje temos o tempo da jornada que por default é de 8 horas, algumas regras da CLT como turno máximo de 6 horas, descanso de pelo menos 1 hora, tempo dentre os dias de no mínimo 11 horas, se tivéssemos configurações disso, acho que facilitaria até pra mostrar o horário que você pode ou não passar o ponto.

Faz sentido?

**Comment by brunozrk** [comment]
Sim, faz sentido, o kadu começou a fazer um mas parou, rsrs

https://github.com/brunozrk/click/pull/24
